#pragma once
#include <array>
#include <string>
#include <vector>
/***********************************************************************
 * Copyright:    (C) 2023 cmfrydos
 * License:      GNU General Public License version 2 or later.
 *
 *               This program is free software; you can redistribute it and/or
 *               modify it under the terms of the GNU General Public License
 *               as published by the Free Software Foundation; either version 2
 *               of the License, or (at your option) any later version.
 *
 *               This program is distributed in the hope that it will be useful,
 *               but WITHOUT ANY WARRANTY; without even the implied warranty of
 *               MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *               GNU General Public License for more details.
 *
 *               You should have received a copy of the GNU General Public
 *License along with this program; if not, write to the Free Software
 *Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
 ***********************************************************************/

// Mostly generated by ChatGPT4 to compute SHA1 Hashes

class sha1 {
	std::array<uint32_t, 5> h_;
	uint64_t processed_bytes_;
	std::vector<uint8_t> buffer_;

	static uint32_t left_rotate(uint32_t value, size_t count);

public:
	sha1();
	void update(const uint8_t* data, size_t len);
	std::array<uint32_t, 5> finalize();
	void process_chunk();
};

std::string get_vector_hash(const std::vector<uint8_t>& data);
std::string get_file_hash(const std::string& filename);